Repository corca-ai/EVAL, pull requests merged in 2023-04, with the labels that each got.

#11 Feature/log better
  ansi.py
  api/main.py
  core/agents/callback.py
  core/agents/manager.py
  logger.py
Labels: feature request

#12 stdout/stderr tracer
  ansi.py
  api/main.py
  core/agents/builder.py
  core/agents/callback.py
  core/agents/llm.py
  core/agents/parser.py
  core/prompts/input.py
  core/tools/editor/__init__.py
  core/tools/editor/patch.py
  core/tools/terminal/__init__.py
  core/tools/terminal/stdout.py
Labels: feature request

#23 Create LICENSE
  LICENSE
Labels: documentation

#22 feat: model_name as an env, and check accessability to the model
  README.md
  core/agents/builder.py
  core/agents/llm.py
  env.py
Labels: feature request

#27 fix: add image handler exception
  core/handlers/base.py
Labels: invalid

#28 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#31 Feature/async inference
  README.md
  api/container.py
  api/main.py
  api/templates/base.html
  api/templates/index.html
  api/worker.py
  assets/gui.png
  core/agents/builder.py
  core/agents/callback.py
  core/agents/manager.py
  core/agents/parser.py
  core/prompts/input.py
  docker-compose.yml
  env.py
  poetry.lock
  pyproject.toml
  static/execute.js
  static/styles.css
Labels: feature request

#30 fix: typo in gpu.py
  core/tools/gpu.py
Labels: bug

#16 fix: more specific CodeEditor.WRITE description prompt
  core/tools/editor/__init__.py
  static/execute.js
Labels: bug
